//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B_Aplication.ServiceReference_Ventas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClienteModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private decimal PrecioField;
        
        private short ExistenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short Existencia {
            get {
                return this.ExistenciaField;
            }
            set {
                if ((this.ExistenciaField.Equals(value) != true)) {
                    this.ExistenciaField = value;
                    this.RaisePropertyChanged("Existencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleVentaModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleVentaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaVentaModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaVentaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int IdVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Ventas.WebVentasSoap")]
    public interface WebVentasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClientes", ReplyAction="*")]
        _3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse GetAllClientes(_3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse> GetAllClientesAsync(_3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProductos", ReplyAction="*")]
        _3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse GetAllProductos(_3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse> GetAllProductosAsync(_3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idCliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarVenta", ReplyAction="*")]
        _3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse RegistrarVenta(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse> RegistrarVentaAsync(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClientes", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequestBody Body;
        
        public GetAllClientesRequest() {
        }
        
        public GetAllClientesRequest(_3B_Aplication.ServiceReference_Ventas.GetAllClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllClientesRequestBody {
        
        public GetAllClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.GetAllClientesResponseBody Body;
        
        public GetAllClientesResponse() {
        }
        
        public GetAllClientesResponse(_3B_Aplication.ServiceReference_Ventas.GetAllClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.ClienteModel[] GetAllClientesResult;
        
        public GetAllClientesResponseBody() {
        }
        
        public GetAllClientesResponseBody(_3B_Aplication.ServiceReference_Ventas.ClienteModel[] GetAllClientesResult) {
            this.GetAllClientesResult = GetAllClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductos", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequestBody Body;
        
        public GetAllProductosRequest() {
        }
        
        public GetAllProductosRequest(_3B_Aplication.ServiceReference_Ventas.GetAllProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductosRequestBody {
        
        public GetAllProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.GetAllProductosResponseBody Body;
        
        public GetAllProductosResponse() {
        }
        
        public GetAllProductosResponse(_3B_Aplication.ServiceReference_Ventas.GetAllProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.ProductoModel[] GetAllProductosResult;
        
        public GetAllProductosResponseBody() {
        }
        
        public GetAllProductosResponseBody(_3B_Aplication.ServiceReference_Ventas.ProductoModel[] GetAllProductosResult) {
            this.GetAllProductosResult = GetAllProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVenta", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequestBody Body;
        
        public RegistrarVentaRequest() {
        }
        
        public RegistrarVentaRequest(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public _3B_Aplication.ServiceReference_Ventas.DetalleVentaModel[] detalleVenta;
        
        public RegistrarVentaRequestBody() {
        }
        
        public RegistrarVentaRequestBody(string idCliente, _3B_Aplication.ServiceReference_Ventas.DetalleVentaModel[] detalleVenta) {
            this.idCliente = idCliente;
            this.detalleVenta = detalleVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponseBody Body;
        
        public RegistrarVentaResponse() {
        }
        
        public RegistrarVentaResponse(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _3B_Aplication.ServiceReference_Ventas.RespuestaVentaModel RegistrarVentaResult;
        
        public RegistrarVentaResponseBody() {
        }
        
        public RegistrarVentaResponseBody(_3B_Aplication.ServiceReference_Ventas.RespuestaVentaModel RegistrarVentaResult) {
            this.RegistrarVentaResult = RegistrarVentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebVentasSoapChannel : _3B_Aplication.ServiceReference_Ventas.WebVentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebVentasSoapClient : System.ServiceModel.ClientBase<_3B_Aplication.ServiceReference_Ventas.WebVentasSoap>, _3B_Aplication.ServiceReference_Ventas.WebVentasSoap {
        
        public WebVentasSoapClient() {
        }
        
        public WebVentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebVentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebVentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebVentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.GetAllClientes(_3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest request) {
            return base.Channel.GetAllClientes(request);
        }
        
        public _3B_Aplication.ServiceReference_Ventas.ClienteModel[] GetAllClientes() {
            _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest inValue = new _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequestBody();
            _3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse retVal = ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).GetAllClientes(inValue);
            return retVal.Body.GetAllClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse> _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.GetAllClientesAsync(_3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest request) {
            return base.Channel.GetAllClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllClientesResponse> GetAllClientesAsync() {
            _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest inValue = new _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.GetAllClientesRequestBody();
            return ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).GetAllClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.GetAllProductos(_3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest request) {
            return base.Channel.GetAllProductos(request);
        }
        
        public _3B_Aplication.ServiceReference_Ventas.ProductoModel[] GetAllProductos() {
            _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest inValue = new _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequestBody();
            _3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse retVal = ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).GetAllProductos(inValue);
            return retVal.Body.GetAllProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse> _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.GetAllProductosAsync(_3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest request) {
            return base.Channel.GetAllProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.GetAllProductosResponse> GetAllProductosAsync() {
            _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest inValue = new _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.GetAllProductosRequestBody();
            return ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).GetAllProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.RegistrarVenta(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVenta(request);
        }
        
        public _3B_Aplication.ServiceReference_Ventas.RespuestaVentaModel RegistrarVenta(string idCliente, _3B_Aplication.ServiceReference_Ventas.DetalleVentaModel[] detalleVenta) {
            _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest inValue = new _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.detalleVenta = detalleVenta;
            _3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse retVal = ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).RegistrarVenta(inValue);
            return retVal.Body.RegistrarVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse> _3B_Aplication.ServiceReference_Ventas.WebVentasSoap.RegistrarVentaAsync(_3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_3B_Aplication.ServiceReference_Ventas.RegistrarVentaResponse> RegistrarVentaAsync(string idCliente, _3B_Aplication.ServiceReference_Ventas.DetalleVentaModel[] detalleVenta) {
            _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest inValue = new _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequest();
            inValue.Body = new _3B_Aplication.ServiceReference_Ventas.RegistrarVentaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.detalleVenta = detalleVenta;
            return ((_3B_Aplication.ServiceReference_Ventas.WebVentasSoap)(this)).RegistrarVentaAsync(inValue);
        }
    }
}
